Repository Udayraj123/OMRChecker, pull requests merged in 2022-10, with the labels that each got.

#51 fix: template.json typos; stack suffix; string formatting
  CONTRIBUTING.md
  samples/sample1/template.json
  samples/sample4/template.json
  src/processors/CropOnMarkers.py
  src/utils/imgutils.py
Labels: bug, hacktoberfest

#56 fix: resolved 'FigureCanvasTkAgg' object has no attribute 'set_window_title' (Issue #55)
  src/utils/imgutils.py
Labels: bug, help wanted, good first issue, hacktoberfest, up-for-grabs

#59 Changed the Installation procedure to make it more readable
  README.md
Labels: hacktoberfest

#63 fix: TypeError: unsupported operand type(s) for *: 'DotMap' and 'float' (issue#62)
  src/processors/CropOnMarkers.py
Labels: bug, hacktoberfest

#69 [Linux] Pip module not found issue added to readme
  README.md
Labels: good first issue, hacktoberfest

#64 Added new sample and its template.json
  samples/community/Antibodyy/simple_omr_sheet.jpg
  samples/community/Antibodyy/template.json
  samples/sample2/AdrianSample/adrian_omr_2.png
Labels: good first issue, hacktoberfest, first-timers-only

#76 reduced the size of omr-1.png
  samples/community/Sandeep-1507/omr-1.png
Labels: hacktoberfest

#60 Adding schema validation for template configuration
  requirements.txt
  src/constants.py
  src/defaults/schema.json
  src/template.py
  src/utils/file.py
Labels: hacktoberfest, intermediate

#81 Dynamic Contribution Section
  Contributors.md
  README.md
Labels: hacktoberfest

#84 fix: Displays stack upto 5 for `show_image_level=1` also
  src/utils/imgutils.py
Labels: hacktoberfest

#87 fix: fixes merged templates using deepcopy function
  src/template.py
Labels: good first issue, hacktoberfest, up-for-grabs

#95 Remove Bad Rolls Directory
  src/constants.py
  src/core.py
  src/utils/imgutils.py
Labels: hacktoberfest

#77 Added basic logging with rich handler
  .gitignore
  main.py
  src/__init__.py
  src/core.py
  src/defaults/config.json
  src/logger.py
  src/processors/CropOnMarkers.py
  src/processors/CropPage.py
  src/processors/manager.py
  src/template.py
  src/utils/__init__.py
  src/utils/file.py
  src/utils/imgutils.py
Labels: enhancement, hacktoberfest, intermediate, review help

#96 Adding pre-commit hook for auto code formatting
  .github/pre-commit.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  requirements.dev.txt
Labels: enhancement, hacktoberfest
